# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Go Project

on:
  push:
    branches: ["andrew"] # Using my branch to test
  pull_request:
    branches: ["andrew"] # Using my branch to test

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            GOOS: linux
            GOARCH: amd64
          - os: macos-latest
            GOOS: darwin
            GOARCH: arm64
          - os: windows-latest
            GOOS: windows
            GOARCH: amd64

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable" # Use latest stable version (see here https://github.com/actions/go-versions/blob/main/versions-manifest.json)

      # Basically runs `go build {operating system}`
      - name: Build
        run: |
          GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.GOARCH }} go build -o build/${{ matrix.GOOS }}_${{ matrix.GOARCH }}/project-starbyte cmd/project-starbyte/main.go

      #- name: Test
      #  run: go test -v ./...
