name: Build cross-platform Go project

on:
  push:
    branches: ["andrew"]

jobs:
  build:
    # TEMP: The runners use the native OS (Mac for Mac, Linux for Linux, etc.). This is very expensive cloud compute time.
    runs-on: ${{ matrix.os }}
    env:
      VERSION: "1.0.0-beta" # Remember to bump the version number before release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            GOOS: linux
            GOARCH: amd64
          - os: ubuntu-latest
            GOOS: linux
            GOARCH: arm64
          - os: macos-latest
            GOOS: darwin
            GOARCH: amd64
          - os: macos-latest
            GOOS: darwin
            GOARCH: arm64
          - os: windows-latest
            GOOS: windows
            GOARCH: amd64
          - os: windows-latest
            GOOS: windows
            GOARCH: arm64
      fail-fast: false # Don't stop the build if one fails

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      # This package is necessary for go module ebitengine/oto to work on Linux
      - name: Install ALSA development package
        if: matrix.GOOS == 'linux'
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev

      - name: Create build directory
        run: mkdir -p build/${{ matrix.GOOS }}_${{ matrix.GOARCH }}

      - name: Build
        # Use native compilation for each platform
        run: |
          if [ "${{ matrix.GOOS }}" = "windows" ]; then
            CGO_ENABLED=1 go build -o build/${{ matrix.GOOS }}_${{ matrix.GOARCH }}/project-starbyte.exe cmd/project-starbyte/main.go
          else
            CGO_ENABLED=1 go build -o build/${{ matrix.GOOS }}_${{ matrix.GOARCH }}/project-starbyte cmd/project-starbyte/main.go
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-starbyte-${{ env.VERSION }}-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: |
            build/${{ matrix.GOOS }}_${{ matrix.GOARCH }}/project-starbyte
            build/${{ matrix.GOOS }}_${{ matrix.GOARCH }}/project-starbyte.exe
