name: Build cross-platform Go project

on:
  push:
    branches: ["andrew"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: "1.0.0-beta" # Remember to bump the version number before release
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]
        include:
          - os: ubuntu-latest
            GOOS: linux
          - os: macos-latest
            GOOS: darwin
          - os: windows-latest
            GOOS: windows

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      # This package is necessary for go module ebitengine/oto to work on Linux
      - name: Install ALSA development package
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev

      - name: Create build directory
        run: mkdir -p build/${{ matrix.GOOS }}_${{ matrix.arch }}

      - name: Build
        run: |
          if [ "${{ matrix.GOOS }}" = "windows" ]; then
            GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.arch }} go build -o build/${{ matrix.GOOS }}_${{ matrix.arch }}/project-starbyte.exe cmd/project-starbyte/main.go
          else
            GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.arch }} go build -o build/${{ matrix.GOOS }}_${{ matrix.arch }}/project-starbyte cmd/project-starbyte/main.go
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          # For example, the folder name will be: project-starbyte-1.0.0-beta-windows-amd64
          name: project-starbyte-${{ env.VERSION }}-${{ matrix.GOOS }}-${{ matrix.arch }}
          path: |
            build/${{ matrix.GOOS }}_${{ matrix.arch }}/project-starbyte-${{ env.VERSION }}-${{ matrix.GOOS }}-${{ matrix.arch }}
            build/${{ matrix.GOOS }}_${{ matrix.arch }}/project-starbyte-${{ env.VERSION }}-${{ matrix.GOOS }}-${{ matrix.arch }}.exe
